name = "stage-transition-maker"
main = "worker.js"
compatibility_date = "2024-01-15"

[site]
bucket = "./dist"

[[route]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

[vars]
# Environment variables will be set via Cloudflare Dashboard

[build]
command = "npm run build"