// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrwxutoukpeirkedntmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyd3h1dG91a3BlaXJrZWRudG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTUwODUsImV4cCI6MjA2ODMzMTA4NX0.IWPLyA8dTBvV1ikKYCwC4QGOr9j_O57sbmp-m448Rac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});